#!/usr/bin/env python3
"""
Run Qwen2.5-VL baseline extraction on sampled receipt/invoice images.

Input:
    outputs/samples/sroie_train_sample_10.jsonl

Each JSONL line should contain:
{
  "json_path": "...",
  "doc_id": "...",
  "image_path": "...",
  "split": "train",
  "source": "sroie2019",
  "document_type": "receipt",
  "image_exists": true
}

Output:
    outputs/baseline/qwen_train_sample_10_v1.jsonl

Each output line contains:
{
  "doc_id": "...",
  "json_path": "...",
  "image_path": "...",
  "ground_truth_fields": {...},
  "prediction": {...},
  "parse_success": true,
  "error": null
}

This script is intended for:
1. sample_10 smoke test
2. sample_30 prompt debugging
3. sample_100 baseline v1
"""

from __future__ import annotations

import argparse
import json
import sys
import traceback
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional


# Make project root importable when running:
# python scripts/run_qwen_baseline.py ...
PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from models.qwen_vl_extractor import extract_fields  # noqa: E402


DEFAULT_SAMPLE_JSONL = (
    "/work/bigweather/xinyanxie/invoiceguard-ai/"
    "outputs/samples/sroie_train_sample_10.jsonl"
)

DEFAULT_OUTPUT = (
    "/work/bigweather/xinyanxie/invoiceguard-ai/"
    "outputs/baseline/qwen_train_sample_10_v1.jsonl"
)


def read_jsonl(path: Path) -> Iterable[Dict[str, Any]]:
    """
    Read JSONL file line by line.
    """
    if not path.exists():
        raise FileNotFoundError(f"Sample JSONL not found: {path}")

    with path.open("r", encoding="utf-8") as f:
        for line_idx, line in enumerate(f, start=1):
            line = line.strip()

            if not line:
                continue

            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(
                    f"Failed to parse JSONL line {line_idx} in {path}: {exc}"
                ) from exc

            if not isinstance(record, dict):
                raise ValueError(
                    f"JSONL line {line_idx} is not an object in {path}"
                )

            yield record


def read_unified_json(json_path: str | Path | None) -> Dict[str, Any]:
    """
    Read the unified JSON generated by preprocess_sroie.py.

    If missing, return empty dict instead of failing the entire run.
    """
    if not json_path:
        return {}

    path = Path(json_path)

    if not path.exists():
        return {}

    try:
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)

        if isinstance(data, dict):
            return data

    except Exception:
        return {}

    return {}


def extract_ground_truth_fields(unified: Dict[str, Any]) -> Dict[str, Any]:
    """
    Extract ground-truth fields from unified JSON.

    In your preprocessing output, data["fields"][field_name]["value"]
    stores the SROIE entity value with evidence/bbox/confidence.
    """
    fields = unified.get("fields", {})

    if not isinstance(fields, dict):
        return {}

    gt: Dict[str, Any] = {}

    for field_name, field_obj in fields.items():
        if isinstance(field_obj, dict):
            gt[field_name] = field_obj.get("value")
        else:
            gt[field_name] = field_obj

    return gt


def build_output_record(
    sample_record: Dict[str, Any],
    prediction: Dict[str, Any],
    error: Optional[str] = None,
    traceback_text: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Build one output JSONL record.
    """
    json_path = sample_record.get("json_path")
    unified = read_unified_json(json_path)
    ground_truth_fields = extract_ground_truth_fields(unified)

    parse_success = bool(prediction.get("_parse_success", False))

    return {
        "doc_id": sample_record.get("doc_id"),
        "original_doc_id": sample_record.get("original_doc_id"),
        "json_path": json_path,
        "image_path": sample_record.get("image_path"),
        "split": sample_record.get("split"),
        "source": sample_record.get("source"),
        "document_type": sample_record.get("document_type"),
        "ground_truth_fields": ground_truth_fields,
        "prediction": prediction,
        "parse_success": parse_success,
        "error": error,
        "traceback": traceback_text,
    }


def write_record(output_path: Path, record: Dict[str, Any]) -> None:
    """
    Append one record to output JSONL.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def load_existing_doc_ids(output_path: Path) -> set[str]:
    """
    Load doc_ids already written to output file.

    Used by --resume to skip completed samples.
    """
    done: set[str] = set()

    if not output_path.exists():
        return done

    with output_path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            if not line:
                continue

            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                continue

            doc_id = record.get("doc_id")
            if doc_id:
                done.add(str(doc_id))

    return done


def empty_prediction_for_error(reason: str, error: str) -> Dict[str, Any]:
    """
    Create a prediction-like object when inference fails before model output.
    """
    return {
        "fields": {},
        "line_items": [],
        "overall_confidence": 0.0,
        "missing_fields": ["INFERENCE_ERROR"],
        "document_quality_issues": [reason],
        "_parse_success": False,
        "_parse_error": error,
        "_raw_model_output": None,
    }


def summarize_output(output_path: Path) -> Dict[str, Any]:
    """
    Summarize parse success and errors from output JSONL.
    """
    stats = {
        "total": 0,
        "parse_success": 0,
        "parse_failed": 0,
        "inference_errors": 0,
    }

    if not output_path.exists():
        return stats

    with output_path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            if not line:
                continue

            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                continue

            stats["total"] += 1

            if record.get("parse_success"):
                stats["parse_success"] += 1
            else:
                stats["parse_failed"] += 1

            if record.get("error"):
                stats["inference_errors"] += 1

    return stats

def get_pred_field_value(prediction: Dict[str, Any], field_name: str) -> Any:
    """
    Safely get prediction.fields[field_name].value.
    """
    fields = prediction.get("fields", {})

    if not isinstance(fields, dict):
        return None

    field_obj = fields.get(field_name)

    if isinstance(field_obj, dict):
        return field_obj.get("value")

    return field_obj


def print_field_preview(output_path: Path, max_examples: int = 10) -> None:
    """
    Print GT vs Pred preview for quick smoke-test inspection.

    This is not the final evaluation. It is only for quick debugging after
    running Qwen baseline.
    """
    if not output_path.exists():
        print(f"[WARN] Cannot preview. Output file not found: {output_path}")
        return

    print()
    print("=== Field Preview: Ground Truth vs Prediction ===")

    shown = 0

    with output_path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            if not line:
                continue

            try:
                r = json.loads(line)
            except json.JSONDecodeError:
                continue

            prediction = r.get("prediction", {})
            gt = r.get("ground_truth_fields", {})

            print("=" * 80)
            print("doc_id:", r.get("doc_id"))

            print("GT vendor:", gt.get("vendor_name"))
            print("Pred vendor:", get_pred_field_value(prediction, "vendor_name"))

            print("GT date:", gt.get("invoice_date"))
            print("Pred date:", get_pred_field_value(prediction, "invoice_date"))

            print("GT total:", gt.get("total"))
            print("Pred total:", get_pred_field_value(prediction, "total"))

            print("Parse success:", r.get("parse_success"))

            parse_error = prediction.get("_parse_error")
            if parse_error:
                print("Parse error:", parse_error)

            shown += 1

            if shown >= max_examples:
                break

    if shown == 0:
        print("[WARN] No valid records found for preview.")


def run_baseline(
    sample_jsonl: Path,
    output_path: Path,
    prompt_path: Optional[Path],
    limit: Optional[int],
    resume: bool,
    overwrite: bool,
) -> None:
    """
    Run Qwen baseline extraction on sampled images.
    """
    if overwrite and output_path.exists():
        output_path.unlink()

    completed_doc_ids = load_existing_doc_ids(output_path) if resume else set()

    sample_records = list(read_jsonl(sample_jsonl))

    if limit is not None:
        sample_records = sample_records[:limit]

    print("=== Qwen Baseline Run ===")
    print(f"Sample JSONL: {sample_jsonl}")
    print(f"Output path:  {output_path}")
    print(f"Prompt path:  {prompt_path if prompt_path else '[built-in prompt]'}")
    print(f"Samples:      {len(sample_records)}")
    print(f"Resume:       {resume}")
    print(f"Overwrite:    {overwrite}")
    print()

    for idx, sample_record in enumerate(sample_records, start=1):
        doc_id = str(sample_record.get("doc_id", "UNKNOWN_DOC"))
        image_path = sample_record.get("image_path")

        if resume and doc_id in completed_doc_ids:
            print(f"[{idx}/{len(sample_records)}] SKIP completed: {doc_id}")
            continue

        print(f"[{idx}/{len(sample_records)}] Processing: {doc_id}")
        print(f"  image: {image_path}")

        if not image_path or not Path(image_path).exists():
            error = f"image path missing or does not exist: {image_path}"
            prediction = empty_prediction_for_error(
                reason="IMAGE_NOT_FOUND",
                error=error,
            )

            out_record = build_output_record(
                sample_record=sample_record,
                prediction=prediction,
                error=error,
                traceback_text=None,
            )

            write_record(output_path, out_record)
            print(f"  [ERROR] {error}")
            continue

        try:
            prediction = extract_fields(
                image_path=image_path,
                prompt_path=prompt_path,
            )

            out_record = build_output_record(
                sample_record=sample_record,
                prediction=prediction,
                error=None,
                traceback_text=None,
            )

            write_record(output_path, out_record)

            parse_success = prediction.get("_parse_success", False)
            print(f"  parse_success: {parse_success}")

        except Exception as exc:
            error = str(exc)
            tb = traceback.format_exc()

            prediction = empty_prediction_for_error(
                reason="INFERENCE_EXCEPTION",
                error=error,
            )

            out_record = build_output_record(
                sample_record=sample_record,
                prediction=prediction,
                error=error,
                traceback_text=tb,
            )

            write_record(output_path, out_record)

            print(f"  [FAILED] {error}")

    stats = summarize_output(output_path)

    print()
    print("=== Baseline Summary ===")
    print(f"Output:            {output_path}")
    print(f"Total records:     {stats['total']}")
    print(f"Parse success:     {stats['parse_success']}")
    print(f"Parse failed:      {stats['parse_failed']}")
    print(f"Inference errors:  {stats['inference_errors']}")

    if stats["total"]:
        rate = stats["parse_success"] / stats["total"] * 100
        print(f"Parse success rate: {rate:.1f}%")
    print_field_preview(output_path, max_examples=min(10, stats["total"]))


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run Qwen2.5-VL extraction baseline on sampled receipts."
    )

    parser.add_argument(
        "--sample-jsonl",
        type=str,
        default=DEFAULT_SAMPLE_JSONL,
        help="Path to sampled JSONL file generated by sample_manifest.py.",
    )

    parser.add_argument(
        "--output",
        type=str,
        default=DEFAULT_OUTPUT,
        help="Output JSONL path for Qwen baseline predictions.",
    )

    parser.add_argument(
        "--prompt",
        type=str,
        default=None,
        help=(
            "Optional prompt txt file. "
            "If not provided, use built-in INVOICE_EXTRACTION_PROMPT."
        ),
    )

    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional maximum number of samples to process.",
    )

    parser.add_argument(
        "--resume",
        action="store_true",
        help="Skip doc_ids that already exist in the output JSONL.",
    )

    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Delete existing output file before running.",
    )

    args = parser.parse_args()

    sample_jsonl = Path(args.sample_jsonl)
    output_path = Path(args.output)
    prompt_path = Path(args.prompt) if args.prompt else None

    if args.resume and args.overwrite:
        raise ValueError("Use either --resume or --overwrite, not both.")

    run_baseline(
        sample_jsonl=sample_jsonl,
        output_path=output_path,
        prompt_path=prompt_path,
        limit=args.limit,
        resume=args.resume,
        overwrite=args.overwrite,
    )


if __name__ == "__main__":
    main()
