#!/usr/bin/env python3
"""
Sample unified SROIE JSON files from a manifest.

Input:
    data/unified/sroie2019/train/manifest.json

The manifest is expected to be a JSON list of unified JSON paths, e.g.
[
  "data/unified/sroie2019/train/sroie_train_X51005200931.json",
  "data/unified/sroie2019/train/sroie_train_X51005230605.json"
]

Output:
    outputs/samples/sroie_train_sample_10.json
    outputs/samples/sroie_train_sample_10.jsonl

The .json output stores a list of paths.
The .jsonl output stores one record per line with useful metadata:
{
  "json_path": "...",
  "doc_id": "...",
  "image_path": "...",
  "split": "train",
  "source": "sroie2019"
}
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path
from typing import Any, Dict, List


DEFAULT_MANIFEST = (
    "/work/bigweather/xinyanxie/invoiceguard-ai/"
    "data/unified/sroie2019/train/manifest.json"
)

DEFAULT_OUTPUT_DIR = (
    "/work/bigweather/xinyanxie/invoiceguard-ai/"
    "outputs/samples"
)


def load_manifest(manifest_path: Path) -> List[Path]:
    """
    Load manifest.json generated by preprocess_sroie.py.

    Expected format:
        [
          "path/to/sample1.json",
          "path/to/sample2.json"
        ]
    """
    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest not found: {manifest_path}")

    with manifest_path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, list):
        raise ValueError(
            f"Manifest must be a JSON list of paths, got: {type(data)}"
        )

    json_paths = [Path(p) for p in data]

    if not json_paths:
        raise ValueError(f"Manifest is empty: {manifest_path}")

    return json_paths


def read_unified_json(json_path: Path) -> Dict[str, Any]:
    """
    Read one unified JSON file.
    """
    if not json_path.exists():
        raise FileNotFoundError(f"Unified JSON not found: {json_path}")

    with json_path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, dict):
        raise ValueError(f"Unified JSON is not an object: {json_path}")

    return data


def build_jsonl_record(json_path: Path) -> Dict[str, Any]:
    """
    Build a compact sample record for JSONL output.

    The full unified JSON is not duplicated here. This file is used as
    a lightweight sampling manifest for later Qwen inference.
    """
    data = read_unified_json(json_path)

    return {
        "json_path": str(json_path),
        "doc_id": data.get("doc_id"),
        "original_doc_id": data.get("original_doc_id"),
        "image_path": data.get("image_path"),
        "split": data.get("split"),
        "source": data.get("source"),
        "document_type": data.get("document_type"),
    }


def sample_paths(
    json_paths: List[Path],
    sample_size: int,
    seed: int,
) -> List[Path]:
    """
    Randomly sample paths from the manifest.

    If sample_size is larger than the available dataset size, return all paths
    in random order instead of failing.
    """
    if sample_size <= 0:
        raise ValueError(f"sample_size must be positive, got: {sample_size}")

    rng = random.Random(seed)

    paths = list(json_paths)
    rng.shuffle(paths)

    if sample_size >= len(paths):
        return paths

    return paths[:sample_size]


def write_json_list(output_path: Path, sampled_paths: List[Path]) -> None:
    """
    Write sampled unified JSON paths as a JSON list.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w", encoding="utf-8") as f:
        json.dump(
            [str(p) for p in sampled_paths],
            f,
            indent=2,
            ensure_ascii=False,
        )


def write_jsonl(output_path: Path, sampled_paths: List[Path]) -> None:
    """
    Write sampled records as JSONL.

    Each line contains useful metadata for later inference.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    missing_images = 0

    with output_path.open("w", encoding="utf-8") as f:
        for json_path in sampled_paths:
            record = build_jsonl_record(json_path)

            image_path = record.get("image_path")
            if not image_path or not Path(image_path).exists():
                missing_images += 1
                record["image_exists"] = False
            else:
                record["image_exists"] = True

            f.write(json.dumps(record, ensure_ascii=False) + "\n")

    if missing_images:
        print(f"[WARN] Sample contains {missing_images} missing image paths.")


def infer_split_name(manifest_path: Path) -> str:
    """
    Infer split name from manifest path.

    Example:
        data/unified/sroie2019/train/manifest.json -> train
    """
    parent_name = manifest_path.parent.name

    if parent_name:
        return parent_name

    return "unknown"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Randomly sample unified SROIE JSON files from manifest.json."
    )

    parser.add_argument(
        "--manifest",
        type=str,
        default=DEFAULT_MANIFEST,
        help="Path to manifest.json generated by preprocess_sroie.py.",
    )

    parser.add_argument(
        "--output-dir",
        type=str,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory where sampled manifest files will be saved.",
    )

    parser.add_argument(
        "--sample-size",
        type=int,
        default=100,
        help="Number of samples to draw.",
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducible sampling.",
    )

    parser.add_argument(
        "--name",
        type=str,
        default=None,
        help=(
            "Optional output name prefix. "
            "Default: sroie_<split>_sample_<sample_size>"
        ),
    )

    args = parser.parse_args()

    manifest_path = Path(args.manifest)
    output_dir = Path(args.output_dir)

    json_paths = load_manifest(manifest_path)

    sampled_paths = sample_paths(
        json_paths=json_paths,
        sample_size=args.sample_size,
        seed=args.seed,
    )

    split_name = infer_split_name(manifest_path)

    if args.name:
        output_prefix = args.name
    else:
        output_prefix = f"sroie_{split_name}_sample_{len(sampled_paths)}"

    output_json = output_dir / f"{output_prefix}.json"
    output_jsonl = output_dir / f"{output_prefix}.jsonl"

    write_json_list(output_json, sampled_paths)
    write_jsonl(output_jsonl, sampled_paths)

    print("=== Sampling Summary ===")
    print(f"Input manifest:        {manifest_path}")
    print(f"Total available:       {len(json_paths)}")
    print(f"Requested sample size: {args.sample_size}")
    print(f"Actual sample size:    {len(sampled_paths)}")
    print(f"Random seed:           {args.seed}")
    print(f"Output JSON:           {output_json}")
    print(f"Output JSONL:          {output_jsonl}")


if __name__ == "__main__":
    main()